{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "refinery.redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "refinery.redis.labels" . | nindent 4 }}
  {{- with .Values.redis.annotations }}
    annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.redis.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
  {{- include "refinery.redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.podAnnotations .Values.redis.podAnnotations }}
      annotations:
      {{- with .Values.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      labels:
    {{- include "refinery.redis.selectorLabels" . | nindent 8 }}
    {{- with .Values.redis.extraLabels}}
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.redis.podLabels}}
      {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "refinery.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          {{- with .Values.redis.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}